version: '3.8'

services:
  user-service:
    image: main-controller:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  listening-service:
    image: listening-service:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge